/** 25.02.2013 17:50 */
package fabric.module.midgen4j.websockets;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Set;
import java.util.HashSet;
import java.util.Properties;

import de.uniluebeck.sourcegen.Workspace;
import de.uniluebeck.sourcegen.js.JSClass;
import de.uniluebeck.sourcegen.js.JSCommentImpl;
import de.uniluebeck.sourcegen.js.JSField;
import de.uniluebeck.sourcegen.js.JSFunction;
import de.uniluebeck.sourcegen.js.JSMethod;
import de.uniluebeck.sourcegen.js.JSSourceFile;
import de.uniluebeck.sourcegen.plaintext.PlainTextFile;
import fabric.module.api.FDefaultWSDLHandler;

import fabric.wsdlschemaparser.wsdl.FOperation;
import fabric.wsdlschemaparser.wsdl.FPortType;

/**
 * Fabric handler class to extend the Java Middleware Generator. This
 * handler is part of the MidGen4J-WebSockets extension and generates
 * the client-side code to use the Atmosphere framework. Atmosphere
 * provides technical means to connect both, a Java server and a
 * JavaScript client, via WebSockets and a variety of other Comet
 * technologies (e.g. streaming and long-polling).
 *
 * On the client-side, Atmosphere uses the jQuery library to open
 * a WebSocket connection and manage all messages. However, the
 * code that is generated by this Fabric handler, will also create
 * a dispatcher class that implements a higher-level RPC protocol
 * on top of WebSockets.
 *
 * For more information about the Atmoshere framework see:
 *   https://github.com/Atmosphere/atmosphere
 *
 * @author seidel
 */
public class AtmosphereJQueryGenerator extends FDefaultWSDLHandler
{
  /** Logger object */
  private static final Logger LOGGER = LoggerFactory.getLogger(AtmosphereJQueryGenerator.class);

  /** Name of the WebSockets test client in HTML file */
  public static final String TEST_CLIENT_NAME = "WebSockets Test Client";

  /** Workspace object for code write-out */
  private Workspace workspace;

  /** Properties object for module configuration */
  private Properties properties;

  /** Service operations from WSDL file */
  private Set<FOperation> operations;

  /**
   * Constructor initializes the AtmosphereJQueryGenerator, which
   * can create the client-side part of the WebSockets service
   * interface.
   *
   * @param workspace Workspace object for source code write-out
   * @param properties Properties object with module options
   */
  public AtmosphereJQueryGenerator(Workspace workspace, Properties properties) throws Exception
  {
    this.workspace = workspace;
    this.properties = properties;

    this.operations = new HashSet<FOperation>();
  }

  /**
   * Create JavaScript code to control the Atmosphere framework and
   * to provide a higher-level RPC protocol on top of WebSockets,
   * before processing any other element of the WSDL document.
   *
   * @throws Exception Error during code generation
   */
  @Override
  public void executeBeforeProcessing() throws Exception
  {
    // Create WebSockets client
    this.createClientApplication();
  }

  /**
   * Create a test client in HTML with controls to call each RPC
   * method from a webbrowser. Furthermore, generate JavaScript
   * code for all service operations.
   *
   * The service operations will be collected in processPortTypes()
   * and can then be used further here, after processing any other
   * element of the WSDL document.
   *
   * @throws Exception Error during code generation
   */
  @Override
  public void executeAfterProcessing() throws Exception
  {
    // Create files for WebSockets test client
    this.createJavaScriptLogger();
    this.createButtonsStyleSheet();
    this.createTestClient(this.operations);

    // Create JavaScript code with RPC methods
    for (FOperation operation: this.operations)
    {
      this.addRpcMethod(operation);
    }
  }

  /**
   * Process port types (WSDL 2.0: interfaces) that are defined in WSDL document.
   *
   * @param portTypes Port types of WSDL document
   *
   * @throws Exception Error during processing
   */
  @Override
  public void processPortTypes(final HashSet<FPortType> portTypes) throws Exception
  {
    // Process all service operations
    for (FPortType portType: portTypes)
    {
      for (FOperation operation: portType.getOperations())
      {
        // Collect all service operations
        this.operations.add(operation);
      }
    }
  }

  /**
   * Create JavaScript application that serves as a WebSockets
   * client in the webbrowser. The generated code controls the
   * Atmosphere framework and provides a higher-level RPC protocol
   * on top of WebSockets.
   *
   * @throws Exception Error during code generation
   */
  private void createClientApplication() throws Exception
  {
    JSSourceFile jssf = this.workspace.getJavaScript().getJSSourceFile(
            this.properties.getProperty(MidGen4JWebSocketsModule.PROJECT_PATH_KEY) + "/webapp/javascript",
            this.properties.getProperty(MidGen4JWebSocketsModule.JS_APPLICATION_NAME_KEY));

    // Add code before fields
    jssf.getCodeBeforeFields().setCode("\'use strict\';");

    // Add global fields
    jssf.add(JSField.factory.create("socket").setComment(new JSCommentImpl("Reference to Atmosphere\'s main client object.")));
    jssf.add(JSField.factory.create("request").setComment(new JSCommentImpl("Object for sending requests to server.")));
    jssf.add(JSField.factory.create("subSocket").setComment(new JSCommentImpl("Subscribed socket with actual connection to server.")));
    jssf.add(JSField.factory.create("dispatcher").setComment(new JSCommentImpl("Manager for tracked RPC method calls.")));

    // Create GUID and dispatcher class
    jssf.add(this.createGUIDClass());
    jssf.add(this.createDispatcherClass());

    // Add global function to open connection
    JSFunction openConnection = JSFunction.factory.create("openConnection");
    openConnection.setComment(new JSCommentImpl("Open connection to server."));
    String methodBody =
            "subSocket = socket.subscribe(request);\n\n" +
            "dispatcher = new Dispatcher(subSocket);";
    openConnection.getBody().setCode(methodBody);
    jssf.add(openConnection);

    // Add global function to close connection
    JSFunction closeConnection = JSFunction.factory.create("closeConnection");
    closeConnection.setComment(new JSCommentImpl("Close connection to server."));
    methodBody = "socket.unsubscribe();";
    closeConnection.getBody().setCode(methodBody);
    jssf.add(closeConnection);

    // Add global function to send message
    JSFunction sendMessage = JSFunction.factory.create("sendMessage", "message");
    sendMessage.setComment(new JSCommentImpl("Send untracked message to server."));
    methodBody =
            "logMessage(\'Now sending untracked message \\'\' + message + \'\\'.\');\n\n" +
            "// This bypasses the tracking mechanism!\n" +
            "subSocket.push(message);";
    sendMessage.getBody().setCode(methodBody);
    jssf.add(sendMessage);

    // Add code to end of file
    jssf.getCodeAfterFunctions().setCode(this.createAtmosphereJQueryCode());
  }

  /**
   * Create a JavaScript class that can generate globally unique
   * identifiers (GUIDs). The GUIDs will later be used to identify
   * messages, which are sent accross the WebSocket connection to
   * call remote methods.
   *
   * @return JSClass object with GUID generator class
   *
   * @throws Exception Error during code generation
   */
  private JSClass createGUIDClass() throws Exception
  {
    // Create GUID class
    JSClass guidClass = JSClass.factory.create("GUID");
    guidClass.setComment(new JSCommentImpl("Helper class to generate unique IDs."));

    // Create helper method to generate random strings
    JSMethod s4 = JSMethod.factory.create("S4");
    s4.setComment(new JSCommentImpl("Create a block of four random characters."));
    String methodBody =
            "return Math.floor(\n" +
            "\tMath.random() * 0x10000 /* 65536 */\n" +
            ").toString(16);";
    s4.getBody().setCode(methodBody);
    guidClass.add(s4);

    // Create a method to generate GUIDs
    JSMethod create = JSMethod.factory.create("create");
    create.setComment(new JSCommentImpl("Return a new GUID."));
    methodBody =
            "return (\n" +
            "\tthis.S4() + this.S4() + \'-\' +\n" +
            "\tthis.S4() + \'-\' +\n" +
            "\tthis.S4() + \'-\' +\n" +
            "\tthis.S4() + \'-\' +\n" +
            "\tthis.S4() + this.S4() + this.S4()\n" +
            ");";
    create.getBody().setCode(methodBody);
    guidClass.add(create);

    return guidClass;
  }

  /**
   * Create a JavaScript class that can track WebSocket messages
   * by their unique ID and is able to dispatch responses to the
   * custom callback functions, that were defined before issuing
   * the RPC method call.
   *
   * @return JSClass object with dispatcher class
   *
   * @throws Exception Error during code generation
   */
  private JSClass createDispatcherClass() throws Exception
  {
    // Create dispatcher class
    JSClass dispatcherClass = JSClass.factory.create("Dispatcher", "subSocket");
    dispatcherClass.setComment(new JSCommentImpl("Dispatcher class to handle RPC methods and track messages."));

    // Add member field for delimiter
    JSField delimiter = JSField.factory.create("delimiter", "\'$\'");
    delimiter.setComment(new JSCommentImpl("Delimiter for protocol parts."));
    dispatcherClass.add(delimiter);

    // Add member field for connection to server
    JSField socket = JSField.factory.create("socket", "subSocket");
    socket.setComment(new JSCommentImpl("Connection to server."));
    dispatcherClass.add(socket);

    // Add member field for pending messages
    JSField pendingMessages = JSField.factory.create("pendingMessages", "new Object()");
    pendingMessages.setComment(new JSCommentImpl("List of pending messages."));
    dispatcherClass.add(pendingMessages);

    // Add method to do a tracked RPC method call
    JSMethod trackedCall = JSMethod.factory.create("trackedCall", "method", "payload", "callback");
    trackedCall.setComment(new JSCommentImpl("Execute tracked RPC method call."));
    String methodBody =
            "var uuid = new GUID().create();\n\n" +
            "// Add call to pending messages\n" +
            "this.pendingMessages[uuid] = callback;\n\n" +
            "logMessage(\'Now tracking call of method \\'\' + method + \'()\\' with GUID \\'\' + uuid + \'\\'.\');\n\n" +
            "this.socket.push(uuid + this.delimiter + method + this.delimiter + payload);";
    trackedCall.getBody().setCode(methodBody);
    dispatcherClass.add(trackedCall);

    // Add method to dispatch response messages
    JSMethod dispatch = JSMethod.factory.create("dispatch", "response");
    dispatch.setComment(new JSCommentImpl("Dispatch response of a tracked message."));
    methodBody =
            "var data = response.split(this.delimiter);\n\n" +

            "if (data.length != 3) {\n" +
            "\tlogMessage(\'Invalid message format. This is not an RPC response.\');\n" +
            "}\n" +
            "else {\n" +
            "\tvar uuid = data[0];\n" +
            "\tvar method = data[1];\n" +
            "\tvar payload = data[2];\n\n" +

            "\t// UUID lookup\n" +
            "\tif (!(uuid in this.pendingMessages)) {\n" +
            "\t\tlogMessage(\'Response with untracked message ID.\');\n" +
            "\t}\n" +
            "\telse {\n" +
            "\t\t// Pass payload to registered callback\n" +
            "\t\tif (this.pendingMessages[uuid] != undefined && typeof this.pendingMessages[uuid] == 'function') {\n" +
            "\t\t\tlogMessage(\'Now dispatching result of method \\'\' + method + \'()\\' with UUID \\'\' + uuid + \'\\'.\');\n\n" +

            "\t\t\t// Execute callback method\n" +
            "\t\t\tthis.pendingMessages[uuid](payload);\n\n" +

            "\t\t\t// Remove call from pending list\n" +
            "\t\t\tdelete this.pendingMessages[uuid];\n" +
            "\t\t}\n" +
            "\t\telse {\n" +
            "\t\t\tlogMessage(\'Could not execute callback.\');\n" +
            "\t\t}\n" +
            "\t}\n" +
            "}";
    dispatch.getBody().setCode(methodBody);
    dispatcherClass.add(dispatch);

    return dispatcherClass;
  }

  /**
   * Create code that is executed by jQuery, as soon as the DOM tree
   * finished loading. The code is used to define parameters for the
   * WebSockets connection and to declare callback methods on the
   * request object which is provided by the Atmosphere framework.
   *
   * @return String with a block of JavaScript code
   */
  private String createAtmosphereJQueryCode()
  {
    String codeBlock = "";

    codeBlock = String.format(
            "/**\n" +
            " * Establish connection to server and define callbacks.\n" +
            " *\n" +
            " * Will be called by jQuery, as soon as DOM is ready.\n" +
            " */\n" +
            "$(function()\n" +
            "{\n" +
            "\tsocket = $.atmosphere;\n\n" +

            "\t// Also see:\n" +
            "\t//   https://github.com/Atmosphere/atmosphere/wiki/jQuery.atmosphere.js-API\n" +
            "\trequest = new $.atmosphere.AtmosphereRequest();\n" +
            "\trequest.url = document.location.toString() + \'%s\';\n" +
            "\trequest.contentType = \'application/json\';\n" +
            "\trequest.transport = \'%s\';\n" +
            "\trequest.fallbackTransport = \'%s\';\n" +
            "\trequest.shared = true;\n" +
            "\trequest.enableXDR = true;\n" +
            "\trequest.headers = { \'Access-Control-Allow-Origin\': \'*\' };\n\n" + // TODO: Do we really need this?

            "\trequest.onOpen = function(response) {\n" +
            "\t\tlogMessage(\'Connection opened.\');\n" +
            "\t\tlogMessage(\'Now connected to \\\'\' + request.url + \'\\\'.\', LogTarget.LOG);\n" +
            "\t}\n\n" +

            "\trequest.onClose = function(response) {\n" +
            "\t\tlogMessage(\'Connection closed.\');\n" +
            "\t}\n\n" +

            "\trequest.onTransportFailure = function(request) {\n" +
            "\t\tlogMessage(\'This browser or the remote server does not support WebSockets.\');\n" +
            "\t}\n\n" +

            "\trequest.onMessage = function(response) {\n" +
            "\t\tvar message = response.responseBody;\n\n" +
            "\t\tlogMessage(\'Message received: \\'\' + message + \'\\'\');\n" +
            "\t\tdispatcher.dispatch(message);\n" +
            "\t}\n" +

            "});",
            this.properties.getProperty(MidGen4JWebSocketsModule.CHANNEL_NAME_KEY),
            this.properties.getProperty(MidGen4JWebSocketsModule.TRANSPORT_KEY),
            this.properties.getProperty(MidGen4JWebSocketsModule.FALLBACK_TRANSPORT_KEY));

    return codeBlock;
  }

  /**
   * Create a JavaScript file with a logger that can be used to
   * print debug and error messages to a variety of log targets
   * (i.e. a textarea, console.log() or an alert() window). The
   * logger is used within the WebSockets test client.
   *
   * @throws Exception Error during code generation
   */
  private void createJavaScriptLogger() throws Exception
  {
    JSSourceFile jssf = this.workspace.getJavaScript().getJSSourceFile(
            this.properties.getProperty(MidGen4JWebSocketsModule.PROJECT_PATH_KEY) + "/webapp/javascript",
            "logger");

    // Add global enum
    String enumDefinition =
            "var LogTarget =\n" +
            "{\n" +
            "\tCONSOLE: 1, // HTML console textarea\n" +
            "\tLOG:     2, // JavaScript console.log() function\n" +
            "\tALERT:   4  // JavaScript alert() function\n" +
            "};";
    jssf.getCodeBeforeFunctions().setCode(enumDefinition);

    // Add global function to log messages
    JSFunction logMessage = JSFunction.factory.create("logMessage", "message", "target");
    logMessage.setComment(new JSCommentImpl("Print message to desired log target."));
    String methodBody =
            "target = typeof target !== 'undefined' ? target : LogTarget.CONSOLE | LogTarget.LOG;\n\n" +
            "if (target & LogTarget.CONSOLE)\n" +
            "{\n" +
            "\tvar consoleWindow = document.getElementById('console');\n\n" +
            
            "\tconsoleWindow.value += createLogLine(message);\n" +
            "\tconsoleWindow.scrollTop = consoleWindow.scrollHeight;\n" +
            "}\n\n" +

            "if (target & LogTarget.LOG)\n" +
            "{\n" +
            "\tconsole.log(message);\n" +
            "}\n\n" +
            
            "if (target & LogTarget.ALERT)\n" +
            "{\n" +
            "\talert(message);\n" +
            "}";
    logMessage.getBody().setCode(methodBody);
    jssf.add(logMessage);

    // Add global function to create log line
    JSFunction createLogLine = JSFunction.factory.create("createLogLine", "message");
    createLogLine.setComment(new JSCommentImpl("Create log message with date and time."));
    methodBody =
            "var now = new Date();\n\n" +

            "var date = fill(now.getDate()) + '.' + fill(now.getMonth() + 1) + '.' + now.getFullYear();\n" +
            "var time = fill(now.getHours()) + ':' + fill(now.getMinutes()) + ':' + fill(now.getSeconds());\n\n" +

            "return '[' + date + ' ' + time + '] ' + message + '\\n';";
    createLogLine.getBody().setCode(methodBody);
    jssf.add(createLogLine);

    // Add global function to fill number with leading zero
    JSFunction fill = JSFunction.factory.create("fill", "number");
    fill.setComment(new JSCommentImpl("Add leading zero to a number."));
    methodBody =
            "return (number > 9 ? number : '0' + number);";
    fill.getBody().setCode(methodBody);
    jssf.add(fill);
  }

  /**
   * Create a CSS file that is used to style control buttons
   * in the WebSockets test client, which is generated by
   * createTestClient().
   */
  private void createButtonsStyleSheet()
  {
    PlainTextFile textFile = this.workspace.getPlainText().getPlainTextFile(
            this.properties.getProperty(MidGen4JWebSocketsModule.PROJECT_PATH_KEY) + "/webapp/css",
            "buttons", "css");

    // Create file content
    String fileContent =
"/**\n" +
" * Button definition.\n" +
" */\n" +
".button\n" +
"{\n" +
"  display: inline-block;\n\n" +

"  /* IE7 hack for display: inline-block */\n" +
"  zoom: 1;\n" +
"  *display: inline; /* The asterisk is intended! */\n" +
"  /* Hack end */\n\n" +

"  margin: 0 2px;\n" +
"  padding: 0.5em 2em 0.55em;\n\n" +

"  vertical-align: baseline;\n" +
"  outline: none;\n\n" +

"  font-family: Helvetica, Arial, sans-serif;\n" +
"  font-size: 14px;\n" +
"  text-align: center;\n" +
"  text-decoration: none;\n" +
"  text-shadow: 0 1px 1px rgba(0, 0, 0, 0.3);\n\n" +

"  cursor: pointer;\n\n" +

"  -moz-border-radius: 0.5em;\n" +
"  -webkit-border-radius: 0.5em;\n" +
"  -khtml-border-radius: 0.5em;\n" +
"  border-radius: 0.5em;\n\n" +

"  -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);\n" +
"  -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);\n" +
"  -khtml-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);\n" +
"  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);\n" +
"}\n\n" +

".button:hover\n" +
"{\n" +
"  text-decoration: none;\n" +
"}\n\n" +

".button:active\n" +
"{\n" +
"  position: relative;\n" +
"  top: 1px;\n" +
"}\n\n\n" +


"/**\n" +
" * Button forms and sizes.\n" +
" */\n" +
".bigrounded\n" +
"{\n" +
"  -moz-border-radius: 2em;\n" +
"  -webkit-border-radius: 2em;\n" +
"  -khtml-border-radius: 2em;\n" +
"  border-radius: 2em;\n" +
"}\n\n" +

".medium\n" +
"{\n" +
"  padding: 0.4em 1.5em 0.42em;\n" +
"  font-size: 12px;\n" +
"}\n\n" +

".small\n" +
"{\n" +
"  padding: 0.2em 1em 0.275em;\n" +
"  font-size: 11px;\n" +
"}\n\n\n" +


"/**\n" +
" * Button color styles.\n" +
" */\n\n" +

"/**\n" +
" * Black button.\n" +
" */\n" +
".black\n" +
"{\n" +
"  color: #D7D7D7;\n" +
"  border: 1px solid #333333;\n" +
"  background-color: #333333;\n" +
"  background: -moz-linear-gradient(top, #666666, #000000);\n" +
"  background: -webkit-linear-gradient(top, #666666, #000000);\n" +
"  background: -khtml-linear-gradient(top, #666666, #000000);\n" +
"  background: linear-gradient(top, #666666, #000000);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#666666', endColorstr='#000000');\n" +
"}\n\n" +

".black:hover\n" +
"{\n" +
"  background-color: #000000;\n" +
"  background: -moz-linear-gradient(top, #444444, #000000);\n" +
"  background: -webkit-linear-gradient(top, #444444, #000000);\n" +
"  background: -khtml-linear-gradient(top, #444444, #000000);\n" +
"  background: linear-gradient(top, #444444, #000000);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#444444', endColorstr='#000000');\n" +
"}\n\n" +

".black:active\n" +
"{\n" +
"  color: #666666;\n" +
"  background: -moz-linear-gradient(top, #000000, #444444);\n" +
"  background: -webkit-linear-gradient(top, #000000, #444444);\n" +
"  background: -khtml-linear-gradient(top, #000000, #444444);\n" +
"  background: linear-gradient(top, #000000, #444444);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#000000', endColorstr='#444444');\n" +
"}\n\n" +

"/**\n" +
" * Gray button.\n" +
" */\n" +
".gray\n" +
"{\n" +
"  color: #E9E9E9;\n" +
"  border: 1px solid #555555;\n" +
"  background-color: #6E6E6E;\n" +
"  background: -moz-linear-gradient(top, #888888, #575757);\n" +
"  background: -webkit-linear-gradient(top, #888888, #575757);\n" +
"  background: -khtml-linear-gradient(top, #888888, #575757);\n" +
"  background: linear-gradient(top, #888888, #575757);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#888888', endColorstr='#575757');\n" +
"}\n\n" +

".gray:hover\n" +
"{\n" +
"  background-color: #616161;\n" +
"  background: -moz-linear-gradient(top, #757575, #4B4B4B);\n" +
"  background: -webkit-linear-gradient(top, #757575, #4B4B4B);\n" +
"  background: -khtml-linear-gradient(top, #757575, #4B4B4B);\n" +
"  background: linear-gradient(top, #757575, #4B4B4B);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#757575', endColorstr='#4B4B4B');\n" +
"}\n\n" +

".gray:active\n" +
"{\n" +
"  color: #AFAFAF;\n" +
"  background: -moz-linear-gradient(top, #575757, #888888);\n" +
"  background: -webkit-linear-gradient(top, #575757, #888888);\n" +
"  background: -khtml-linear-gradient(top, #575757, #888888);\n" +
"  background: linear-gradient(top, #575757, #888888);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#575757', endColorstr='#888888');\n" +
"}\n\n" +

"/**\n" +
" * White button.\n" +
" */\n" +
".white\n" +
"{\n" +
"  color: #606060;\n" +
"  border: 1px solid #B7B7B7;\n" +
"  background-color: #FFFFFF;\n" +
"  background: -moz-linear-gradient(top, #FFFFFF, #EDEDED);\n" +
"  background: -webkit-linear-gradient(top, #FFFFFF, #EDEDED);\n" +
"  background: -khtml-linear-gradient(top, #FFFFFF, #EDEDED);\n" +
"  background: linear-gradient(top, #FFFFFF, #EDEDED);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FFFFFF', endColorstr='#EDEDED');\n" +
"}\n\n" +

".white:hover\n" +
"{\n" +
"  background-color: #EDEDED;\n" +
"  background: -moz-linear-gradient(top, #FFFFFF, #DCDCDC);\n" +
"  background: -webkit-linear-gradient(top, #FFFFFF, #DCDCDC);\n" +
"  background: -khtml-linear-gradient(top, #FFFFFF, #DCDCDC);\n" +
"  background: linear-gradient(top, #FFFFFF, #DCDCDC);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FFFFFF', endColorstr='#DCDCDC');\n" +
"}\n\n" +

".white:active\n" +
"{\n" +
"  color: #999999;\n" +
"  background: -moz-linear-gradient(top, #EDEDED, #FFFFFF);\n" +
"  background: -webkit-linear-gradient(top, #EDEDED, #FFFFFF);\n" +
"  background: -khtml-linear-gradient(top, #EDEDED, #FFFFFF);\n" +
"  background: linear-gradient(top, #EDEDED, #FFFFFF);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#EDEDED', endColorstr='#FFFFFF');\n" +
"}\n\n" +

"/**\n" +
" * Orange button.\n" +
" */\n" +
".orange\n" +
"{\n" +
"  color: #FEF4E9;\n" +
"  border: 1px solid #DA7C0C;\n" +
"  background-color: #F78D1D;\n" +
"  background: -moz-linear-gradient(top, #FAA51A, #F47A20);\n" +
"  background: -webkit-linear-gradient(top, #FAA51A, #F47A20);\n" +
"  background: -khtml-linear-gradient(top, #FAA51A, #F47A20);\n" +
"  background: linear-gradient(top, #FAA51A, #F47A20);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FAA51A', endColorstr='#F47A20');\n" +
"}\n\n" +

".orange:hover\n" +
"{\n" +
"  background-color: #F47C20;\n" +
"  background: -moz-linear-gradient(top, #F88E11, #F06015);\n" +
"  background: -webkit-linear-gradient(top, #F88E11, #F06015);\n" +
"  background: -khtml-linear-gradient(top, #F88E11, #F06015);\n" +
"  background: linear-gradient(top, #F88E11, #F06015);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#F88E11', endColorstr='#F06015');\n" +
"}\n\n" +

".orange:active\n" +
"{\n" +
"  color: #FCD3A5;\n" +
"  background: -moz-linear-gradient(top, #F47A20, #FAA51A);\n" +
"  background: -webkit-linear-gradient(top, #F47A20, #FAA51A);\n" +
"  background: -khtml-linear-gradient(top, #F47A20, #FAA51A);\n" +
"  background: linear-gradient(top, #F47A20, #FAA51A);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#F47A20', endColorstr='#FAA51A');\n" +
"}\n\n" +

"/**\n" +
" * Red button.\n" +
" */\n" +
".red\n" +
"{\n" +
"  color: #FADDDE;\n" +
"  border: 1px solid #980C10;\n" +
"  background-color: #D81B21;\n" +
"  background: -moz-linear-gradient(top, #ED1C24, #AA1317);\n" +
"  background: -webkit-linear-gradient(top, #ED1C24, #AA1317);\n" +
"  background: -khtml-linear-gradient(top, #ED1C24, #AA1317);\n" +
"  background: linear-gradient(top, #ED1C24, #AA1317);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ED1C24', endColorstr='#AA1317');\n" +
"}\n\n" +

".red:hover\n" +
"{\n" +
"  background-color: #B61318;\n" +
"  background: -moz-linear-gradient(top, #C9151B, #A11115);\n" +
"  background: -webkit-linear-gradient(top, #C9151B, #A11115);\n" +
"  background: -khtml-linear-gradient(top, #C9151B, #A11115);\n" +
"  background: linear-gradient(top, #C9151B, #A11115);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#C9151B', endColorstr='#A11115');\n" +
"}\n\n" +

".red:active\n" +
"{\n" +
"  color: #DE898C;\n" +
"  background: -moz-linear-gradient(top, #AA1317, #ED1C24);\n" +
"  background: -webkit-linear-gradient(top, #AA1317, #ED1C24);\n" +
"  background: -khtml-linear-gradient(top, #AA1317, #ED1C24);\n" +
"  background: linear-gradient(top, #AA1317, #ED1C24);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#AA1317', endColorstr='#ED1C24');\n" +
"}\n\n" +

"/**\n" +
" * Green button.\n" +
" */\n" +
".green\n" +
"{\n" +
"  color: #E8F0DE;\n" +
"  border: 1px solid #538312;\n" +
"  background-color: #64991E;\n" +
"  background: -moz-linear-gradient(top, #7DB72F, #4E7D0E);\n" +
"  background: -webkit-linear-gradient(top, #7DB72F, #4E7D0E);\n" +
"  background: -khtml-linear-gradient(top, #7DB72F, #4E7D0E);\n" +
"  background: linear-gradient(top, #7DB72F, #4E7D0E);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#7DB72F', endColorstr='#4E7D0E');\n" +
"}\n\n" +

".green:hover\n" +
"{\n" +
"  background-color: #538018;\n" +
"  background: -moz-linear-gradient(top, #6B9D28, #436B0C);\n" +
"  background: -webkit-linear-gradient(top, #6B9D28, #436B0C);\n" +
"  background: -khtml-linear-gradient(top, #6B9D28, #436B0C);\n" +
"  background: linear-gradient(top, #6B9D28, #436B0C);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#6B9D28', endColorstr='#436B0C');\n" +
"}\n\n" +

".green:active\n" +
"{\n" +
"  color: #A9C08C;\n" +
"  background: -moz-linear-gradient(top, #4E7D0E, #7DB72F);\n" +
"  background: -webkit-linear-gradient(top, #4E7D0E, #7DB72F);\n" +
"  background: -khtml-linear-gradient(top, #4E7D0E, #7DB72F);\n" +
"  background: linear-gradient(top, #4E7D0E, #7DB72F);\n" +
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#4E7D0E', endColorstr='#7DB72F');\n" +
"}";

    textFile.getContent().setCode(fileContent);
  }

  /**
   * Create a WebSockets test client in HTML that can be used to
   * call each RPC method of MidGen4J's central service provider.
   * The client can be run in any browser with WebSockets support.
   *
   * @param operations Service operations that need controls
   */
  private void createTestClient(final Set<FOperation> operations)
  {
    PlainTextFile textFile = this.workspace.getPlainText().getPlainTextFile(
            this.properties.getProperty(MidGen4JWebSocketsModule.PROJECT_PATH_KEY) + "/webapp",
            "index", "html");

    // Create controls to call RPC methods
    String rpcControls = this.createRpcControls(operations);

    // Create file content
    String fileContent = String.format(
"<!DOCTYPE html>\n" +
"<html>\n\n" +

"<head>\n" +
"  <title>%s</title>\n\n" +

"  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n\n" +

"  <script type=\"text/javascript\" src=\"./jquery/jquery-1.7.2.js\"></script>\n" +
"  <script type=\"text/javascript\" src=\"./jquery/jquery.atmosphere.js\"></script>\n" +
"  <script type=\"text/javascript\" src=\"./javascript/logger.js\"></script>\n" +
"  <script type=\"text/javascript\" src=\"./javascript/%s.js\"></script>\n\n" +

"  <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"./css/buttons.css\" />\n\n" +

"  <style type=\"text/css\">\n" +
"    body\n" +
"    {\n" +
"      font-family: 'Lucida Grande', 'Bitstream Vera Sans', 'Trebuchet MS', Verdana, Arial, sans-serif;\n" +
"      color: #FF9900;\n" +
"      text-shadow: 2px 2px 2px #555555;\n" +
"      background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAADSCAIAAAAE3T1fAAAAA3NCSVQIC" +
            "Ajb4U/gAAAACXBIWXMAAA2sAAANrAHvBsZHAAAAJXRFWHRTb2Z0d2FyZQBNYWNyb21lZGlhIEZpcmV3b3JrcyBNWCAyMDA0h3" +
            "aszwAAAGFJREFUeJzdkUsKgDAMRF8GmgvlLF6g1/RwuqgFrdYP7hoY8oPJDIEm3F1PSCn1dgDknBURigiWeRIgMGEIVHqr2coO" +
            "u67/zA53tozudXzW03AO5bHDOYLH/f9OnPWvr7ECMg8IAMa/iuoAAAAASUVORK5CYII%%3D');\n" + // %% will escape %
"      background-repeat: repeat-x;\n" +
"    }\n\n" +

"    h1\n" +
"    {\n" +
"      margin: 0;\n" +
"      margin-top: 30px;\n" +
"      margin-bottom: 10px;\n" +
"      padding: 0;\n" +
"      font-size: 48px;\n" +
"      text-align: center;\n" +
"    }\n\n" +

"    div.controls\n" +
"    {\n" +
"      margin: 10px auto;\n" +
"    }\n\n" +

"    div.buttonRow\n" +
"    {\n" +
"      margin-bottom: 10px;\n" +
"      padding: 3px;\n\n" +

"      text-align: center;\n" +
"    }\n\n" +

"    textarea#console\n" +
"    {\n" +
"      display: block;\n" +
"      margin: 0 auto;\n" +
"      padding: 5px;\n\n" +

"      font-family: monospace;\n" +
"      font-size: 12px;\n" +
"      font-weight: bold;\n" +
"      color: #00FF00;\n\n" +

"      background-color: #000000;\n" +
"      border: 5px ridge #CCCCCC;\n" +
"    }\n" +
"  </style>\n" +
"</head>\n\n" +

"<body>\n" +
"  <h1>%s</h1>\n\n" +

"  <textarea id=\"console\" cols=\"102\" rows=\"20\" readonly=\"readonly\"></textarea>\n\n" +

"  <div class=\"controls\">\n" +
"    <div class=\"buttonRow\">\n" +
"      <span class=\"button medium green\" onClick=\"openConnection();\">Open connection</span>\n" +
"      <span class=\"button medium orange\" onClick=\"sendMessage(window.prompt('Enter desired message:', 'uuid$method$payload'));\">Send message</span>\n" +
"      <span class=\"button medium gray\" onClick=\"document.getElementById('console').value = '';\">Clear console</span>\n" +
"      <span class=\"button medium red\" onClick=\"closeConnection();\">Close connection</span>\n" +
"    </div>\n" +
"%s" +
"  </div>\n" +
"</body>\n\n" +

"</html>",
            TEST_CLIENT_NAME, this.properties.getProperty(MidGen4JWebSocketsModule.JS_APPLICATION_NAME_KEY),
            TEST_CLIENT_NAME, rpcControls);

    textFile.getContent().setCode(fileContent);
  }

  /**
   * Private helper method to create a single string that contains
   * controls to call all RPC methods of the service. The controls
   * are grouped in rows of four buttons each.
   *
   * @param operations Service operations that need controls
   */
  private String createRpcControls(final Set<FOperation> operations)
  {
    String result = "";
    int i = 0;

    // Iterate all service operations
    for (FOperation operation: operations)
    {
      // Begin of row
      if (i % 4 == 0)
      {
        result += "\n";
        result += "    <div class=\"buttonRow\">\n";
      }

      // Controls in current row
      result += String.format(
              "      <span class=\"button medium black\" onClick=\"%s();\">Call %s()</span>\n",
              operation.getOperationName(), operation.getOperationName());

      // End of current row or end of last row
      if (i % 4 == 3 || i == operations.size() - 1)
      {
        result += "    </div>\n";
      }

      ++i;
    }

    return result;
  }

  /**
   * Add a global function to the JavaScript application, so that
   * the corresponding RPC method can be called from the WebSockets
   * test client.
   *
   * @param operation Service operation to add as global function
   *
   * @throws Exception Error during code generation
   */
  private void addRpcMethod(final FOperation operation) throws Exception
  {
    JSSourceFile jssf = this.workspace.getJavaScript().getJSSourceFile(
            this.properties.getProperty(MidGen4JWebSocketsModule.PROJECT_PATH_KEY) + "/webapp/javascript",
            this.properties.getProperty(MidGen4JWebSocketsModule.JS_APPLICATION_NAME_KEY));

    String name = operation.getOperationName();
    String inputMessage = (null == operation.getInputMessage() ? "{}" : "{ /* TODO: Add your custom JSON code here */ }");

    // Add global function to call RPC method
    JSFunction rpcFunction = JSFunction.factory.create(name);
    rpcFunction.setComment(new JSCommentImpl(String.format("Call the '%s' remote method.", name)));

    // Set method body
    String methodBody = String.format(
            "if (dispatcher != undefined) {\n" +
            "\tdispatcher.trackedCall(\'%s\', JSON.stringify(%s),\n" +
            "\t\tfunction(response) {\n" +
            "\t\t\tlogMessage('Got response to \\'%s()\\' request: ' + JSON.parse(response).result);\n\n" +
            "\t\t\t/* TODO: Add your custom callback code here */\n" +
            "\t\t});\n" +
            "}",
            name, inputMessage, name);
    rpcFunction.getBody().setCode(methodBody);

    jssf.add(rpcFunction);
  }
}
